# Generated by Django 4.2.6 on 2023-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('production', models.CharField(max_length=1)),
                ('disrtibutor', models.CharField(max_length=1)),
                ('genre', models.CharField(max_length=1)),
                ('price', models.CharField(max_length=1)),
                ('publication_data', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'games1',
                'managed': True,
            },
        ),
    ]
