# Generated by Django 4.2.6 on 2023-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_games1_disrtibutor_alter_games1_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games1',
            name='genre',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='games1',
            name='price',
            field=models.CharField(max_length=55),
        ),
    ]
